[workspace]
members = [ "codama-cli",
	"core",
	"program"
, "sdk"]

resolver = "2"

[workspace.dependencies]
borsh = { version = "0.10.3" }
bytemuck = { version = "1.16.3", features = ["min_const_generics"] }
codama = "0.3.0"
jito-account-traits-derive = { git = "https://github.com/jito-foundation/restaking.git", rev = "9efa55c30b3427d94975b22dcd27a82181c776ba" }
jito-bytemuck = { git = "https://github.com/jito-foundation/restaking.git", rev = "9efa55c30b3427d94975b22dcd27a82181c776ba" }
jito-jsm-core = { git = "https://github.com/jito-foundation/restaking.git", rev = "9efa55c30b3427d94975b22dcd27a82181c776ba" }
solana-pubkey = "~2.1"
solana-program = "~2.1"
solana-sdk = "~2.1"
thiserror = "1.0.57"
vault-whitelist-core = { path = "./core" }
vault-whitelist-sdk = { path = "./sdk" }
