[env]
VAULT_WHITELIST_PROGRAM_ID = "7BHULFc6NKwtc7f2ap6y7ty1cRfTN5MBMfJQj1rxEUhP"
RESTAKING_PROGRAM_ID = "RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"
VAULT_PROGRAM_ID = "Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"
