[package]
name = "vault-whitelist-sdk"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { version = "0.10.3" }
solana-pubkey = { workspace = true }
solana-program = { workspace = true }
shank = { workspace = true }
thiserror = { workspace = true }
