[package]
name = "jito-vault-whitelist-sdk"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true }
shank = { workspace = true }
solana-program = { workspace = true }
thiserror = { workspace = true }
