/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { JITO_VAULT_WHITELIST_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_WHITELIST_DISCRIMINATOR = 8;

export function getCloseWhitelistDiscriminatorBytes() {
  return getU8Encoder().encode(CLOSE_WHITELIST_DISCRIMINATOR);
}

export type CloseWhitelistInstruction<
  TProgram extends string = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountVaultConfig extends string | IAccountMeta<string> = string,
  TAccountWhitelist extends string | IAccountMeta<string> = string,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountVaultAdmin extends string | IAccountMeta<string> = string,
  TAccountJitoVaultProgram extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountVaultConfig extends string
        ? ReadonlyAccount<TAccountVaultConfig>
        : TAccountVaultConfig,
      TAccountWhitelist extends string
        ? WritableAccount<TAccountWhitelist>
        : TAccountWhitelist,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountVaultAdmin extends string
        ? WritableSignerAccount<TAccountVaultAdmin> &
            IAccountSignerMeta<TAccountVaultAdmin>
        : TAccountVaultAdmin,
      TAccountJitoVaultProgram extends string
        ? ReadonlyAccount<TAccountJitoVaultProgram>
        : TAccountJitoVaultProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseWhitelistInstructionData = { discriminator: number };

export type CloseWhitelistInstructionDataArgs = {};

export function getCloseWhitelistInstructionDataEncoder(): Encoder<CloseWhitelistInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: CLOSE_WHITELIST_DISCRIMINATOR })
  );
}

export function getCloseWhitelistInstructionDataDecoder(): Decoder<CloseWhitelistInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getCloseWhitelistInstructionDataCodec(): Codec<
  CloseWhitelistInstructionDataArgs,
  CloseWhitelistInstructionData
> {
  return combineCodec(
    getCloseWhitelistInstructionDataEncoder(),
    getCloseWhitelistInstructionDataDecoder()
  );
}

export type CloseWhitelistInput<
  TAccountConfig extends string = string,
  TAccountVaultConfig extends string = string,
  TAccountWhitelist extends string = string,
  TAccountVault extends string = string,
  TAccountVaultAdmin extends string = string,
  TAccountJitoVaultProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config: Address<TAccountConfig>;
  vaultConfig: Address<TAccountVaultConfig>;
  whitelist: Address<TAccountWhitelist>;
  vault: Address<TAccountVault>;
  vaultAdmin: TransactionSigner<TAccountVaultAdmin>;
  jitoVaultProgram: Address<TAccountJitoVaultProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getCloseWhitelistInstruction<
  TAccountConfig extends string,
  TAccountVaultConfig extends string,
  TAccountWhitelist extends string,
  TAccountVault extends string,
  TAccountVaultAdmin extends string,
  TAccountJitoVaultProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
>(
  input: CloseWhitelistInput<
    TAccountConfig,
    TAccountVaultConfig,
    TAccountWhitelist,
    TAccountVault,
    TAccountVaultAdmin,
    TAccountJitoVaultProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CloseWhitelistInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountVaultConfig,
  TAccountWhitelist,
  TAccountVault,
  TAccountVaultAdmin,
  TAccountJitoVaultProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_VAULT_WHITELIST_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    vaultConfig: { value: input.vaultConfig ?? null, isWritable: false },
    whitelist: { value: input.whitelist ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    vaultAdmin: { value: input.vaultAdmin ?? null, isWritable: true },
    jitoVaultProgram: {
      value: input.jitoVaultProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.vaultConfig),
      getAccountMeta(accounts.whitelist),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultAdmin),
      getAccountMeta(accounts.jitoVaultProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getCloseWhitelistInstructionDataEncoder().encode({}),
  } as CloseWhitelistInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountVaultConfig,
    TAccountWhitelist,
    TAccountVault,
    TAccountVaultAdmin,
    TAccountJitoVaultProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedCloseWhitelistInstruction<
  TProgram extends string = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    vaultConfig: TAccountMetas[1];
    whitelist: TAccountMetas[2];
    vault: TAccountMetas[3];
    vaultAdmin: TAccountMetas[4];
    jitoVaultProgram: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: CloseWhitelistInstructionData;
};

export function parseCloseWhitelistInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCloseWhitelistInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      vaultConfig: getNextAccount(),
      whitelist: getNextAccount(),
      vault: getNextAccount(),
      vaultAdmin: getNextAccount(),
      jitoVaultProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCloseWhitelistInstructionDataDecoder().decode(instruction.data),
  };
}
