/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { JITO_VAULT_WHITELIST_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_WHITELIST_DISCRIMINATOR = 1;

export function getInitializeWhitelistDiscriminatorBytes() {
  return getU8Encoder().encode(INITIALIZE_WHITELIST_DISCRIMINATOR);
}

export type InitializeWhitelistInstruction<
  TProgram extends string = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountWhitelist extends string | IAccountMeta<string> = string,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountVaultAdmin extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountWhitelist extends string
        ? WritableAccount<TAccountWhitelist>
        : TAccountWhitelist,
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountVaultAdmin extends string
        ? WritableSignerAccount<TAccountVaultAdmin> &
            IAccountSignerMeta<TAccountVaultAdmin>
        : TAccountVaultAdmin,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeWhitelistInstructionData = { discriminator: number };

export type InitializeWhitelistInstructionDataArgs = {};

export function getInitializeWhitelistInstructionDataEncoder(): Encoder<InitializeWhitelistInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: INITIALIZE_WHITELIST_DISCRIMINATOR })
  );
}

export function getInitializeWhitelistInstructionDataDecoder(): Decoder<InitializeWhitelistInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getInitializeWhitelistInstructionDataCodec(): Codec<
  InitializeWhitelistInstructionDataArgs,
  InitializeWhitelistInstructionData
> {
  return combineCodec(
    getInitializeWhitelistInstructionDataEncoder(),
    getInitializeWhitelistInstructionDataDecoder()
  );
}

export type InitializeWhitelistInput<
  TAccountConfig extends string = string,
  TAccountWhitelist extends string = string,
  TAccountVault extends string = string,
  TAccountVaultAdmin extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config: Address<TAccountConfig>;
  whitelist: Address<TAccountWhitelist>;
  vault: Address<TAccountVault>;
  vaultAdmin: TransactionSigner<TAccountVaultAdmin>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getInitializeWhitelistInstruction<
  TAccountConfig extends string,
  TAccountWhitelist extends string,
  TAccountVault extends string,
  TAccountVaultAdmin extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
>(
  input: InitializeWhitelistInput<
    TAccountConfig,
    TAccountWhitelist,
    TAccountVault,
    TAccountVaultAdmin,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeWhitelistInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountWhitelist,
  TAccountVault,
  TAccountVaultAdmin,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_VAULT_WHITELIST_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    whitelist: { value: input.whitelist ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: false },
    vaultAdmin: { value: input.vaultAdmin ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.whitelist),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.vaultAdmin),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeWhitelistInstructionDataEncoder().encode({}),
  } as InitializeWhitelistInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountWhitelist,
    TAccountVault,
    TAccountVaultAdmin,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitializeWhitelistInstruction<
  TProgram extends string = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    whitelist: TAccountMetas[1];
    vault: TAccountMetas[2];
    vaultAdmin: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: InitializeWhitelistInstructionData;
};

export function parseInitializeWhitelistInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedInitializeWhitelistInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      whitelist: getNextAccount(),
      vault: getNextAccount(),
      vaultAdmin: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeWhitelistInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
