/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { JITO_VAULT_WHITELIST_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const REMOVE_FROM_WHITELIST_DISCRIMINATOR = 4;

export function getRemoveFromWhitelistDiscriminatorBytes() {
  return getU8Encoder().encode(REMOVE_FROM_WHITELIST_DISCRIMINATOR);
}

export type RemoveFromWhitelistInstruction<
  TProgram extends string = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountWhitelist extends string | IAccountMeta<string> = string,
  TAccountWhitelistUser extends string | IAccountMeta<string> = string,
  TAccountVaultAdmin extends string | IAccountMeta<string> = string,
  TAccountUser extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountWhitelist extends string
        ? ReadonlyAccount<TAccountWhitelist>
        : TAccountWhitelist,
      TAccountWhitelistUser extends string
        ? WritableAccount<TAccountWhitelistUser>
        : TAccountWhitelistUser,
      TAccountVaultAdmin extends string
        ? ReadonlySignerAccount<TAccountVaultAdmin> &
            IAccountSignerMeta<TAccountVaultAdmin>
        : TAccountVaultAdmin,
      TAccountUser extends string
        ? ReadonlyAccount<TAccountUser>
        : TAccountUser,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RemoveFromWhitelistInstructionData = { discriminator: number };

export type RemoveFromWhitelistInstructionDataArgs = {};

export function getRemoveFromWhitelistInstructionDataEncoder(): Encoder<RemoveFromWhitelistInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({
      ...value,
      discriminator: REMOVE_FROM_WHITELIST_DISCRIMINATOR,
    })
  );
}

export function getRemoveFromWhitelistInstructionDataDecoder(): Decoder<RemoveFromWhitelistInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getRemoveFromWhitelistInstructionDataCodec(): Codec<
  RemoveFromWhitelistInstructionDataArgs,
  RemoveFromWhitelistInstructionData
> {
  return combineCodec(
    getRemoveFromWhitelistInstructionDataEncoder(),
    getRemoveFromWhitelistInstructionDataDecoder()
  );
}

export type RemoveFromWhitelistInput<
  TAccountConfig extends string = string,
  TAccountVault extends string = string,
  TAccountWhitelist extends string = string,
  TAccountWhitelistUser extends string = string,
  TAccountVaultAdmin extends string = string,
  TAccountUser extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config: Address<TAccountConfig>;
  vault: Address<TAccountVault>;
  whitelist: Address<TAccountWhitelist>;
  whitelistUser: Address<TAccountWhitelistUser>;
  vaultAdmin: TransactionSigner<TAccountVaultAdmin>;
  user: Address<TAccountUser>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getRemoveFromWhitelistInstruction<
  TAccountConfig extends string,
  TAccountVault extends string,
  TAccountWhitelist extends string,
  TAccountWhitelistUser extends string,
  TAccountVaultAdmin extends string,
  TAccountUser extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
>(
  input: RemoveFromWhitelistInput<
    TAccountConfig,
    TAccountVault,
    TAccountWhitelist,
    TAccountWhitelistUser,
    TAccountVaultAdmin,
    TAccountUser,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): RemoveFromWhitelistInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountVault,
  TAccountWhitelist,
  TAccountWhitelistUser,
  TAccountVaultAdmin,
  TAccountUser,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_VAULT_WHITELIST_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: false },
    whitelist: { value: input.whitelist ?? null, isWritable: false },
    whitelistUser: { value: input.whitelistUser ?? null, isWritable: true },
    vaultAdmin: { value: input.vaultAdmin ?? null, isWritable: false },
    user: { value: input.user ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.whitelist),
      getAccountMeta(accounts.whitelistUser),
      getAccountMeta(accounts.vaultAdmin),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getRemoveFromWhitelistInstructionDataEncoder().encode({}),
  } as RemoveFromWhitelistInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountVault,
    TAccountWhitelist,
    TAccountWhitelistUser,
    TAccountVaultAdmin,
    TAccountUser,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedRemoveFromWhitelistInstruction<
  TProgram extends string = typeof JITO_VAULT_WHITELIST_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    vault: TAccountMetas[1];
    whitelist: TAccountMetas[2];
    whitelistUser: TAccountMetas[3];
    vaultAdmin: TAccountMetas[4];
    user: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: RemoveFromWhitelistInstructionData;
};

export function parseRemoveFromWhitelistInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRemoveFromWhitelistInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      vault: getNextAccount(),
      whitelist: getNextAccount(),
      whitelistUser: getNextAccount(),
      vaultAdmin: getNextAccount(),
      user: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getRemoveFromWhitelistInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
